---
version: 0
sudo: required
dist: trusty
metadata:
  name: "taskcluster-lib-docs"
  description: "Generate, build and upload documents for taskcluster projects"
  licence: "MPL-2.0"
language: node_js
node_js:
  - '0.12'
  - '4'
  - '5'
  - '6'
repository:
  type: "git"
  url: "https://github.com/taskcluster/taskcluster-lib-docs.git"
install:
  npm install
before_script:
  - cp user-config-example.yml user-config.yml
script:
  compile: babel-compile -p taskcluster src:lib test:.test
  prepublish: npm run compile
  pretest: npm run compile
  test: mocha .test/lint.js .test/*_test.js
env:
  global:
    - DEBUG='taskcluster-lib-docs test'
dependencies:
  - aws-sdk
  - babel-runtime
  - lodash
  - mz
  - promise
  - recursive-readdir-sync
  - s3-upload-stream
  - tar-stream
  - taskcluster-base
  - taskcluster-client
devDependencies:
  - babel-compile
  - babel-eslint
  - babel-preset-taskcluster
  - eslint-config-taskcluster
  - eslint-plugin-taskcluster
  - mocha
  - mocha-eslint
  - source-map-support
  - taskcluster-lib-validate
main:
  lib/docs.js
paths:
  test:
    - +:test/**
  source:
    - src/**
